name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        #, macos-14, windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: sensor-firmware

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: sensor-firmware
          toolchains: arm-zephyr-eabi

      - name: Build
        run: |
          west build -b promicro_nrf52840/nrf52840 sensor-firmware/app

      # - name: Twister Tests
      #   working-directory: example-application
      #   shell: bash
      #   run: |
      #     if [ "${{ runner.os }}" = "Windows" ]; then
      #       EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
      #     fi
      #     west twister -T tests -v --inline-logs --integration "$EXTRA_TWISTER_FLAGS"
